# Generated by Django 5.2.5 on 2025-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_technicalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Lucide React icon name (e.g., 'Code', 'Database', 'Server')", max_length=50)),
            ],
        ),
    ]
