# Generated by Django 5.2.5 on 2025-08-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_whatido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('technologies', models.ManyToManyField(related_name='personalinfo', to='about.technicalskill')),
            ],
        ),
    ]
