# Generated by Django 5.2.5 on 2025-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
