# Generated by Django 5.2.5 on 2025-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_personalinfo_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='whatido',
            field=models.ManyToManyField(related_name='personalinfo', to='about.whatido'),
        ),
    ]
