# Generated by Django 5.2.5 on 2025-08-18 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_personalinfo_whatido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_img'),
        ),
    ]
