# Generated by Django 5.2.5 on 2025-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_personalinfo_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
