# Generated by Django 5.2.5 on 2025-08-18 14:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_personalinfo_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
