# Generated by Django 5.2.5 on 2025-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_personalinfo_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
