# Generated by Django 5.2.5 on 2026-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='board_or_university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='score',
            field=models.CharField(blank=True, help_text='Enter Percentage or CGPA (e.g., 85% or 9.2)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
