# Generated by Django 5.2.5 on 2026-03-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_education_board_or_university_education_ongoing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='board_or_university',
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('10TH', '10th Standard'), ('12TH', '12th Standard'), ('DIPLOMA', 'Diploma'), ('BTECH', 'Bachelor of Technology (B.Tech)'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
