# Generated by Django 5.2.5 on 2026-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_remove_education_board_or_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='education',
            field=models.ManyToManyField(related_name='personalinfo', to='about.education'),
        ),
    ]
