# Generated by Django 5.2.5 on 2026-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_personalinfo_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='score',
        ),
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
