# Generated by Django 5.2.5 on 2026-03-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_remove_education_score_education_cgpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='softskills',
            field=models.ManyToManyField(related_name='personalinfo', to='about.softskill'),
        ),
    ]
