# Generated by Django 5.2.5 on 2026-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_softskill_personalinfo_softskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('10TH', 'Matriculation'), ('12TH', 'Intermediate'), ('DIPLOMA', 'Diploma'), ('BTECH', 'Bachelor of Technology (B.Tech)'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
