# Generated by Django 5.2.5 on 2025-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0002_technicalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('github_link', models.URLField()),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('technologies', models.ManyToManyField(related_name='projects', to='about.technicalskill')),
            ],
        ),
    ]
