# Generated by Django 5.2.5 on 2025-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
