# Generated by Django 5.2.5 on 2025-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
    ]
