# Generated by Django 5.2.5 on 2025-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
