# Generated by Django 5.2.5 on 2025-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Get in Touch', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
