# Generated by Django 5.2.5 on 2025-08-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
