# Generated by Django 5.2.5 on 2026-03-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='description',
        ),
    ]
