# Generated by Django 5.2.5 on 2026-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_rename_name_certificates_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
