# Generated by Django 5.2.5 on 2026-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificates_issuing_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='is_mooc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificates',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
    ]
