# Generated by Django 5.2.5 on 2026-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificates_is_mooc_certificates_is_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
